#!/usr/bin/env bash
# Regenerate configs/nvim/lua/custom/brave-commands.lua from upstream source.
# Parses Chromium's chrome_command_ids.h and brave-core's brave_command_ids.h,
# extracts #define IDC_FOO <int>, title-cases the names, writes a Lua table.
#
# Run via `task brave:gen-commands`. Network required.
set -euo pipefail

OUT="$(dirname "$0")/../lua/custom/brave-commands.lua"
CHROMIUM_URL="https://raw.githubusercontent.com/chromium/chromium/main/chrome/app/chrome_command_ids.h"
BRAVE_URL="https://raw.githubusercontent.com/brave/brave-core/master/app/brave_command_ids.h"

{
  printf -- '-- Generated by configs/nvim/scripts/gen-brave-commands.sh. DO NOT EDIT.\n'
  printf -- '-- Source: chromium chrome_command_ids.h + brave-core brave_command_ids.h\n'
  printf -- '-- Regenerate with: task brave:gen-commands\n\n'
  printf 'return {\n'

  (curl -fsSL "$CHROMIUM_URL"; curl -fsSL "$BRAVE_URL") | awk '
    BEGIN {
      # Abbreviations kept uppercase after title-casing
      split("URL DNS HTTP HTTPS PDF AI VPN UI RSS XHR CSS JS HTML XML JSON YAML CSV TLS SSL CA FTP SSH SMTP IP IPV4 IPV6 OS GPU CPU RAM ID IDS UUID GUID API CLI TUI GUI DOM SQL DB IO TOR OCR QR AR VR XR WWW ASCII UTF", list, " ")
      for (i in list) abbr[list[i]] = 1
    }
    /^#define IDC_[A-Z0-9_]+[ \t]+[0-9]+$/ {
      name = $2; sub(/^IDC_/, "", name); id = $3
      n = split(name, p, "_")
      out = ""
      for (i = 1; i <= n; i++) {
        out = out (abbr[p[i]] ? p[i] : substr(p[i],1,1) tolower(substr(p[i],2)))
        if (i < n) out = out " "
      }
      if (!seen[id]++) printf "  [%s] = %c%s%c,\n", id, 34, out, 34
    }
  '

  printf '}\n'
} > "$OUT"

echo "Wrote $(grep -c '^  \[' "$OUT") commands to $OUT"
