---
- name: Check existing config
  stat:
    path: "{{ ansible_env.HOME }}/{{ dotfile }}"
  register: config_stat

- name: Backup existing non-symlink config
  command: mv {{ ansible_env.HOME }}/{{ dotfile }} {{ ansible_env.HOME }}/{{ dotfile }}.backup_{{ ansible_date_time.iso8601 }}
  register: backup_result
  when: config_stat.stat.exists and not config_stat.stat.islnk

- name: Create symlink for config
  file:
    src: "{{ (playbook_dir + '/../configs/' + dotfile) | realpath }}"
    dest: "{{ ansible_env.HOME }}/{{ dotfile }}"
    state: link
  when: not config_stat.stat.exists or not config_stat.stat.islnk 