- name: Set destination file path
  set_fact:
    computed_dest: "{{ dest_file | default(ansible_env.HOME + '/' + dotfile) }}"

- name: Ensure parent directory exists
  file:
    path: "{{ computed_dest | dirname }}"
    state: directory

- name: Check existing config
  stat:
    path: "{{ computed_dest }}"
  register: config_stat

- name: Delete existing non-symlink config
  file:
    path: "{{ computed_dest }}"
    state: absent
  when: 
    - config_stat.stat.exists 
    - not config_stat.stat.islnk
    - delete_existing | default(false) | bool

- name: Backup existing non-symlink config
  command: mv {{ computed_dest }} {{ computed_dest }}.backup_{{ ansible_date_time.iso8601 }}
  when: 
    - config_stat.stat.exists 
    - not config_stat.stat.islnk
    - not (delete_existing | default(false) | bool)

- name: Create symlink for config
  file:
    src: "{{ (playbook_dir + '/../configs/' + dotfile) | realpath }}"
    dest: "{{ computed_dest }}"
    state: "{{ 'file' if (use_copy | default(false))  else 'link' }}"
    force: "{{ overwrite_dest | default(false) }}"
  when: >
    not config_stat.stat.exists or
    not config_stat.stat.islnk or
    (overwrite_dest | default(false) | bool)

