# these 3 hostnames require tailscale and magic DNS resolution
[sftp.streaming-server]
host = "streaming-server"
user = "claude"
port = 22
key_file = "~/.ssh/id_ed25519"


[sftp.degen-bot]
host = "degen-bot"
user = "claude"
port = 22
key_file = "~/.ssh/id_ed25519"

[sftp.pi-box]
host = "pi-box"
user = "claude"
port = 22
key_file = "~/.ssh/id_ed25519"

