# ~/.config/yazi/yazi.toml
[mgr]
linemode = "mtime"
# show_hidden = true
sort_by = "mtime"
sort_reverse = true


[plugin]
  prepend_preloaders = [
    ## from mediainfo plugin
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
    # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
    { mime = "application/postscript", run = "mediainfo" },
    ## from office plugin
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
  ]
  prepend_previewers = [
    ## from ouch plugin
    { mime = "application/*zip",            run = "ouch" },
    { mime = "application/x-tar",           run = "ouch" },
    { mime = "application/x-bzip2",         run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar",           run = "ouch" },
    { mime = "application/vnd.rar",         run = "ouch" },
    { mime = "application/x-xz",            run = "ouch" },
    { mime = "application/xz",              run = "ouch" },
    { mime = "application/x-zstd",          run = "ouch" },
    { mime = "application/zstd",            run = "ouch" },
    { mime = "application/java-archive",    run = "ouch" },
    ## from rich preview plugin
    { name = "*.csv", run = "rich-preview"}, # for csv files
    { name = "*.md", run = "rich-preview" }, # for markdown (.md) files
    { name = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
    { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
    { name = "*.json", run = "rich-preview"}, # for json (.json) files
    ## from mediainfo plugin
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
    # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
    { mime = "application/postscript", run = "mediainfo" },
    ## from office plugin
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
  ]
