filetype plugin indent on
set autoindent
set smartindent

" default ignore case in search
set ignorecase
" Use spaces instead of tabs
set expandtab
" Set shift width (for > and <) to 2 spaces
set shiftwidth=2
" Set tab width to 2 spaces
set tabstop=2
" Keep selection when indenting in visual mode (commeting as seems to break indenting?)
" vnoremap > >gv
" vnoremap < <gv

" Show line numbers
set number

" Show relative line numbers
set relativenumber

" hack for clipboard on wsl
if system('uname -r') =~ "Microsoft"
  augroup Yank
    autocmd!
    autocmd TextYankPost * :call system('/mnt/c/windows/system32/clip.exe ',@")
  augroup END
endif

set clipboard=unnamedplus

" Jump to next/previous URL
nnoremap ]l /https:\/\/<CR>
nnoremap [l ?https:\/\/<CR>

