" load db ext passwords from separate file
if filereadable(expand("~/.vim/dbext_passwords.vim"))
      source ~/.vim/dbext_passwords.vim
endif

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

filetype plugin indent on
set autoindent
set smartindent

" Plugins configuration
call plug#begin()
Plug 'jasonccox/vim-wayland-clipboard'
Plug 'tpope/vim-dadbod'
Plug 'kristijanhusak/vim-dadbod-ui'
Plug 'kristijanhusak/vim-dadbod-completion'
Plug 'vim-scripts/dbext.vim'      
Plug 'preservim/nerdcommenter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-unimpaired'
call plug#end()

" default ignore case in search
set ignorecase
" Use spaces instead of tabs
set expandtab
" Set shift width (for > and <) to 2 spaces
set shiftwidth=2
" Set tab width to 2 spaces
set tabstop=2
" Keep selection when indenting in visual mode (commeting as seems to break indenting?)
" vnoremap > >gv
" vnoremap < <gv

" Show line numbers
set number

" Show relative line numbers
set relativenumber

" hack for clipboard on wsl
if system('uname -r') =~ "Microsoft"
  augroup Yank
    autocmd!
    autocmd TextYankPost * :call system('/mnt/c/windows/system32/clip.exe ',@")
  augroup END
endif

set clipboard=unnamedplus
