# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.z-shell-navigation-tools]
github = "z-shell/zsh-navigation-tools"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

[plugins.git]
github = "davidde/git"

[plugins.zsh-fzf-history-search]
github = "joshskidmore/zsh-fzf-history-search"

[plugins.zsh-output-highlighting]
github = "l4u/zsh-output-highlighting"

[plugins.dracula]
github = "dracula/zsh"

[plugins.colored-man-pages]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/colored-man-pages"

[plugins.wezterm-integration]
remote = "https://raw.githubusercontent.com/wez/wezterm/main/assets/shell-integration/wezterm.sh"

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
